
# Description: This file will read from the output folder generated by 
#	preprocessing.py and feed it though an Artifical Neutral Netowkr. 
# 	Please use read the following link, it will be helpful 
#
#	https://mochajl.readthedocs.io/en/latest/tutorial/mnist.html#preparing-the-data


## Building the Network 



## Solve the Network  
